# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messenger.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmessenger.proto\x12\tmessenger\x1a\x1cgoogle/api/annotations.proto\"I\n\x07Message\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"\x18\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xb4\x01\n\tMessenger\x12L\n\x0bSendMessage\x12\x12.messenger.Message\x1a\x10.messenger.Empty\"\x17\x82\xd3\xe4\x93\x02\x11\"\x0c/v1/messages:\x01*\x12Y\n\x0fReceiveMessages\x12\x0f.messenger.User\x1a\x12.messenger.Message\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/messages/{username}0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messenger_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSENGER'].methods_by_name['SendMessage']._options = None
  _globals['_MESSENGER'].methods_by_name['SendMessage']._serialized_options = b'\202\323\344\223\002\021\"\014/v1/messages:\001*'
  _globals['_MESSENGER'].methods_by_name['ReceiveMessages']._options = None
  _globals['_MESSENGER'].methods_by_name['ReceiveMessages']._serialized_options = b'\202\323\344\223\002\031\022\027/v1/messages/{username}'
  _globals['_MESSAGE']._serialized_start=60
  _globals['_MESSAGE']._serialized_end=133
  _globals['_USER']._serialized_start=135
  _globals['_USER']._serialized_end=159
  _globals['_EMPTY']._serialized_start=161
  _globals['_EMPTY']._serialized_end=168
  _globals['_MESSENGER']._serialized_start=171
  _globals['_MESSENGER']._serialized_end=351
# @@protoc_insertion_point(module_scope)
